version: "3.9"
services:
  app:
    build: .
    depends_on:
      - db
      - es
      - sidekiq
    links:
      - db
    entrypoint: ["docker-entry.sh"]
    command: "rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file: .env
    
  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootp@ss
    restart: always
    ports:
      - "3307:3306"

  redis:
    image: redis:5.0.7
  
  es:
    image: elasticsearch:7.13.1
    environment:
      discovery.type: single-node
  
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    command: bash -c "bundle exec sidekiq"
    depends_on:
      - redis
    env_file: .env

volumes:
  mysql-datavolume: